(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("map",
{ "compressionlevel":0,
 "height":15,
 "infinite":false,
 "layers":[
        {
         "compression":"zlib",
         "data":"eAG1UEEKACAMWvX\/P0cHQWKFRjvErE2ntYhodDrhQZhnFMw6+zx6qHv\/9z3b42QD3+FwBvD5rRI7PjNvCj\/jrUyn98q8mbbr45b51lN2u3xovvLAV6r7T4rm7xn2OAEbkQFN",
         "encoding":"base64",
         "height":15,
         "id":1,
         "name":"BG1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eAG9k90NwjAMhPsAXYBCJ2hhA35WoBu0sBX7ctdiyUnjOnkh0imxff6URHJV5a\/asXp1p31VJk8zD4gbpeOqYzuhWXR2UK90ZrJgxbwrem\/Q5bffC1i0khczCxGB3WJ9Ald+YPEeDmKH+j7hsXgJa5A6IWqDzBJYvH+\/N3G1OSX3k118qf+LPeLVu+XRPP69zIw3L+TFM8beQTGeOL+gN+TNC3ni7XG2NKE2ZvK+HyEJ0w==",
         "encoding":"base64",
         "height":15,
         "id":3,
         "name":"BG2",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eAGtklEOgzAMQ5E4z8bGuA9n2P1\/VgueZLktH6ORgtPEcUPbaTpsP\/FbUI6RZ91Ccbynxcncle7jD73U9\/VnsN5a9Dbf4Ga8DJ5P4+R96EyfKpglx0pVmFzuD6wazkT2wevlqTvqvGVX78z1iH221yFRfcWF78XMMYNziMWdi2cPdWHWdB+485ybPc7zmmJpvYvznz1t1xgRa08\/ZzR9PnJ3EL0fAaoSWQ==",
         "encoding":"base64",
         "height":15,
         "id":5,
         "name":"BG3",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eAFjYKANaAAam48FN5Fp3UQc+tDFG9DsxGUfuj6Y8ejihPi49OESJ9a8JUj+aEZiT0Zig8J3GRAjA3TzkeWwsQmpJySPbiYh9ejy2NIIsn\/R\/UeqfejqCfHR3UdIPSH5wW4ecjoDxcVgBwC9KRvM",
         "encoding":"base64",
         "height":15,
         "id":2,
         "name":"Path",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eAG1jlEKwDAIQ73Mdp7e\/zRbPx4NQboJdTCejTEasb6xytBa5OMle5y6iJ5qnXW2L9O4YdfDM4nPqZ4TNflZFj2oHtf8jRcdfun0oc+hV5nloDnJRued8Y8nm+vWuAt276vmcxec89f739Wgjf8Bs04KTA==",
         "encoding":"base64",
         "height":15,
         "id":4,
         "name":"build",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eAFjYBgF9AqBMnpZRCd7SqlkzzSgOTOAeDoQL6SSmbjcNtzigErBNWSMAQByrwQ9",
         "encoding":"base64",
         "height":15,
         "id":6,
         "name":"test",
         "opacity":1,
         "type":"tilelayer",
         "visible":false,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":7,
         "name":"Path",
         "objects":[
                {
                 "height":0,
                 "id":1,
                 "name":"",
                 "polyline":[
                        {
                         "x":0,
                         "y":-1
                        }, 
                        {
                         "x":135.406,
                         "y":-0.77386
                        }, 
                        {
                         "x":135.334,
                         "y":-112.654
                        }, 
                        {
                         "x":39.3134,
                         "y":-112.654
                        }, 
                        {
                         "x":39.3134,
                         "y":-48.5167
                        }, 
                        {
                         "x":199.365,
                         "y":-49.0167
                        }, 
                        {
                         "x":199.341,
                         "y":-96.9141
                        }, 
                        {
                         "x":263.454,
                         "y":-96.6403
                        }, 
                        {
                         "x":263.454,
                         "y":63.1132
                        }, 
                        {
                         "x":326.146,
                         "y":63.0894
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":0.52386,
                 "y":136.728
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":8,
 "nextobjectid":4,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.10.2",
 "tileheight":16,
 "tilesets":[
        {
         "firstgid":1,
         "source":"assets\/Tilemap.tsx"
        }],
 "tilewidth":16,
 "type":"map",
 "version":"1.10",
 "width":20
});